services:
  blockchain-queue:
    container_name: solpay-blockchain-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_PORT: 8009
      MQ_HOST: solpay-rabbitmq
      MQ_USER: ${MQ_USER}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_VHOST: ${MQ_VHOST}
      MQ_URL: amqp://${MQ_USER}:${MQ_PASSWORD}@solpay-rabbitmq/${MQ_VHOST}
    ports:
      - "8009:8009"
    networks:
      - solpay-core-service_solpay-network

networks:
  solpay-core-service_solpay-network:
    external: true
